In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('../data/iha_hydrodatabase_240919_csv.csv', encoding='latin')
df.head()

,Hydropower Station Name,Database Status,ID,Country,ISO,Reservoir Name,Lake Name,Purpose,Admin_unit,Owner,...,Reference 3,Reference 4,Reference 5,Reference 6,Reference 7,Reference 8,Reference 9,Reference 10,Comment,Column1
0,Kalpong,Matched with hydro station,179,India,IND,NaN,NaN,Hydropower,Andaman & Nicobar,A&N Administration,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Nagarjuna Sagar,Matched with hydro station,28,India,IND,Nagarjuna Sagar,NaN,"Multi-purpose Irrigation, Hydropower",Andhra Pradesh,APGENCO,...,https://upload.wikimedia.org/wikipedia/commons...,https://www.thehindu.com/news/national/andhra-...,http://globalenergyobservatory.org/geoid/4428,https://apgenco.gov.in/getInfo.do,http://nwda.gov.in/upload/uploadfiles/files/92...,https://telanganatoday.com/crisis-stares-at-fa...,http://globalenergyobservatory.org/geoid/4427,http://globalenergyobservatory.org/geoid/4426,The reservoir is located between the borders ...,NaN
2,Penna Ahobilam,Matched with hydro station,29,India,IND,Dr KS Penna Ahobilam Balancing Reservoir,NaN,"Irrigation, Hydropower",Andhra Pradesh,APGENCO,...,https://apgenco.gov.in/getInfo.do,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Also called PABR Dam. The Penna Ahobilam Power...,NaN
3,Srisailam,Matched with hydro station,156,India,IND,Srisailam,NaN,Hydropower,Andhra Pradesh,TSGENCO & APGENCO,...,https://web.archive.org/web/20110721165130/htt...,http://www.contec.co.in/project/single_whole_p...,https://www.indiawaterportal.org/articles/mana...,http://iwm.vassarlabs.com/reservoir/Summary/AL...,https://irrigationap.cgg.gov.in/wrd/static/app...,https://www.scribd.com/document/58789365/Srisa...,https://www.tsgenco.co.in/getInfo.do,NaN,The second largest working hydroelectric stati...,NaN
4,Lower Subansiri,Under construction / stalled,182,India,IND,NaN,NaN,Hydropower,Assam/Arunachal Pradesh,National Hydroelectric Power Corporation (NHPC),...,http://web.iitd.ac.in/~arunku/files/CVL100/eia...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The Subansiri Lower HE Project is the biggest ...,NaN

In [4]:
len(df)

182

In [5]:
df.columns

Index(['Hydropower Station Name', 'Database Status', 'ID', 'Country', 'ISO',
       'Reservoir Name', 'Lake Name', 'Purpose', 'Admin_unit', 'Owner ',
       'Near_city', 'District ', 'River', 'Main_basin', 'Catch_Area ',
       'Op_Status', 'Comissioned', 'DamComplete', 'No_Units', 'Dam_hgt ',
       'WaterHeadhgt( max)', 'WaterHeadHgt (min)', 'Res_capacityMm3',
       'Res_area km2', 'HPP_elec_cap', 'Transm_exist', 'Transm_length',
       'Transm_planned', 'Hydropower_Type', 'Ann_firm_gen', 'Ann_tot_gen',
       'Lat (reservoir/dam)', 'Long (reservoir/dam)',
       'Lat (hydropower station 1)', 'Long (hydropower station 1)',
       'Lat (hydropower station 2)', 'Long (hydropower station 2)', 'Display',
       'Reference 1', 'Reference 2', 'Reference 3', 'Reference 4',
       'Reference 5', 'Reference 6', 'Reference 7', 'Reference 8',
       'Reference 9', 'Reference 10', 'Comment', 'Column1'],
      dtype='object')

In [6]:
df.dtypes

Hydropower Station Name         object
Database Status                 object
ID                               int64
Country                         object
ISO                             object
Reservoir Name                  object
Lake Name                       object
Purpose                         object
Admin_unit                      object
Owner                           object
Near_city                       object
District                        object
River                           object
Main_basin                      object
Catch_Area                      object
Op_Status                       object
Comissioned                     object
DamComplete                    float64
No_Units                        object
Dam_hgt                        float64
WaterHeadhgt( max)             float64
WaterHeadHgt (min)             float64
Res_capacityMm3                float64
Res_area km2                    object
HPP_elec_cap                    object
Transm_exist                    object
Transm_length                  float64
Transm_planned                 float64
Hydropower_Type                 object
Ann_firm_gen                   float64
Ann_tot_gen                    float64
Lat (reservoir/dam)            float64
Long (reservoir/dam)           float64
Lat (hydropower station 1)     float64
Long (hydropower station 1)    float64
Lat (hydropower station 2)     float64
Long (hydropower station 2)    float64
Display                         object
Reference 1                     object
Reference 2                     object
Reference 3                     object
Reference 4                     object
Reference 5                     object
Reference 6                     object
Reference 7                     object
Reference 8                     object
Reference 9                     object
Reference 10                    object
Comment                         object
Column1                         object
dtype: object

In [7]:
df.isnull().sum()

Hydropower Station Name          0
Database Status                  0
ID                               0
Country                          0
ISO                              0
Reservoir Name                 110
Lake Name                      173
Purpose                          0
Admin_unit                       1
Owner                           54
Near_city                        2
District                       138
River                            0
Main_basin                     141
Catch_Area                     161
Op_Status                       60
Comissioned                      0
DamComplete                     62
No_Units                        75
Dam_hgt                          1
WaterHeadhgt( max)             169
WaterHeadHgt (min)             170
Res_capacityMm3                  7
Res_area km2                    26
HPP_elec_cap                    69
Transm_exist                   122
Transm_length                  172
Transm_planned                 176
Hydropower_Type                 36
Ann_firm_gen                   182
Ann_tot_gen                    108
Lat (reservoir/dam)             30
Long (reservoir/dam)            30
Lat (hydropower station 1)      89
Long (hydropower station 1)     89
Lat (hydropower station 2)     171
Long (hydropower station 2)    171
Display                          0
Reference 1                     42
Reference 2                    104
Reference 3                    129
Reference 4                    151
Reference 5                    170
Reference 6                    174
Reference 7                    178
Reference 8                    180
Reference 9                    180
Reference 10                   181
Comment                         88
Column1                        180
dtype: int64

In [8]:
df['WaterHeadhgt( max)'].fillna(df['WaterHeadhgt( max)'].median())

0      140.21
1      140.21
2      140.21
3      140.21
4      140.21
        ...
177    140.21
178    140.21
179    140.21
180    140.21
181    140.21
Name: WaterHeadhgt( max), Length: 182, dtype: float64

In [9]:
df['WaterHeadHgt (min)'].fillna(df['WaterHeadHgt (min)'].median())

0      112.47
1      112.47
2      112.47
3      112.47
4      112.47
        ...
177    112.47
178    112.47
179    112.47
180    112.47
181    112.47
Name: WaterHeadHgt (min), Length: 182, dtype: float64

In [59]:

# df['Res_area km2'].fillna(df['Res_area km2'].median())                   
# HPP_elec_cap 
# pd.to_numeric(df['Res_area km2'])
# print(df['Res_area km2'][51])
# df = df.drop(labels=51, axis=0)
# print(df['Res_area km2'][51])
# df[51:52]
# df = df.drop(labels=153, axis=0)

In [16]:
pd.to_numeric(df['Res_area km2'])
# df['Res_area km2'].unique()
# df[df['Res_area km2'] == '0.647.5']
# df.drop(51,axis=0, inplace=True)

ValueError: Unable to parse string " " at position 155

In [16]:
df[df['HPP_elec_cap'] == '234 + 240']

,Hydropower Station Name,Database Status,ID,Country,ISO,Reservoir Name,Lake Name,Purpose,Admin_unit,Owner,...,Reference 3,Reference 4,Reference 5,Reference 6,Reference 7,Reference 8,Reference 9,Reference 10,Comment,Column1
159,Jurala,Matched with hydro station,25,India,IND,Jurala,NaN,"Irrigation, Hydropower, Multi-purpose",Telangana,Telangana Power Generation Corporation,...,https://www.thehindubusinessline.com/news/nati...,https://en.wikipedia.org/wiki/Lower_Jurala_Hyd...,NaN,NaN,NaN,NaN,NaN,NaN,Jaralu project is located at the southern part...,NaN

In [17]:
df.drop(159,axis=0, inplace=True)

In [18]:
df['HPP_elec_cap'].unique()

array(['5.25', '810', '20', '900', '2000', '10', '120', '240', '1450',
       '305', '990', '396', '180', '540', '800', '1325', '390', '345',
       '690', '480', '63.2', '80', nan, '72', '290', '39.2', '32', '955',
       '56.2', '3', '22.5', '50', '100', '54', '75', '780', '225', '37.5',
       '32.4', '300', '115', '60', '90', '1000', '6', '0.5', '2.5',
       '2.25', '1.5', '8', '16', '1920', '160', '4', '2', '12', '1.6',
       '227.2', '114.75', '510', '347.5', '600', '250', '320', '155.3',
       '140', '172', '400', '40', '30', '161', '95', '150', '35', '27',
       '15', '30.6', '45', '330', '395', '198'], dtype=object)

In [19]:
pd.to_numeric(df['HPP_elec_cap'])

0         5.25
1       810.00
2        20.00
3       900.00
4      2000.00
        ...
177     198.00
178       4.00
179        NaN
180        NaN
181        NaN
Name: HPP_elec_cap, Length: 181, dtype: float64